language: ruby

before_install:
  - sudo apt-get install libzmq3-dev
  - sudo apt-get install zookeeperd

before_script:
  - sleep 15

services:
  - mongodb
  - redis-server
  - cassandra

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2.2.10

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2.2.10
    - env: DCELL_TEST_ADAPTER=cassandra
    - env: DCELL_TEST_ADAPTER=zk

branches:
  only:
    - master

env:
    - DCELL_TEST_ADAPTER=redis
    - DCELL_TEST_ADAPTER=mongodb
    - DCELL_TEST_ADAPTER=cassandra
    - DCELL_TEST_ADAPTER=zk
