language: ruby

before_install:
  - sudo apt-get install libzmq3-dev
  - sudo apt-get install zookeeperd

before_script:
  - sleep 15
  - cassandra-cli --batch < <(echo -e "create keyspace test with placement_strategy = 'org.apache.cassandra.locator.SimpleStrategy' and strategy_options = {replication_factor:1};\nuse test;\ncreate column family dcell;")

services:
  - redis-server
  - cassandra

rvm:
  - 2.0.0
  - 2.1.4
  - 2.2.2
  - ruby-head
  - jruby
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-2
    - env: DCELL_TEST_ADAPTER=cassandra
    - env: DCELL_TEST_ADAPTER=zk

branches:
  only:
    - master

env:
    - DCELL_TEST_ADAPTER=redis
    - DCELL_TEST_ADAPTER=cassandra
    - DCELL_TEST_ADAPTER=zk
